### ISSUE TITLE
Dependency on sqlx

### ISSUE THREAD

**Issue by danilobuerger** [db-journey/postgresql-driver#1]
Apart from legacy, is there a reason we have to depend on sqlx? If not, I would tackle removing it on the weekend.

**Comment by gravis** [comment]
I just find the code easier to read and write.
On the contrary, is there a good reason for _not_ using it?
Check out https://github.com/gemnasium/migrate/commit/a4fb34188a3a867b4d2290c40595b8e94f38f75f#diff-1cf6273eb48ed6deda1dce6b0c75f94aR142
IMHO, `database/sql` is more intended for low level things.

**Comment by danilobuerger** [comment]
It's just one more dependency a user has to pull in. Not everybody is using sqlx in their project, so they would have that dependency only for the migration part. 

Really the only thing that would change is the select in `func (driver *Driver) Versions() (file.Versions, error)`. So it's a tradeoff between 10 more LOCs vs. pulling in a whole library that depends on even more reflection to get the job done.

**Comment by gravis** [comment]
Understood. Ok, go for it then.
Thanks!

**Comment by danilobuerger** [comment]
Will do on the weekend
